---
- debug:
      var: ssl

- name: Nginx | Create SSL directories
  become: yes
  file:
      path: "{{ ssl_dir_name }}"
      state: directory
  with_items:
      - "/etc/nginx/ssl/{{ ssl.name }}"
      - "/etc/nginx/snippets/{{ ssl.name }}"
  loop_control:
      loop_var: ssl_dir_name

- name: Nginx | Copy SSL certificates
  become: yes
  copy:
      src: "{{ item }}"
      dest: "/etc/nginx/ssl/{{ ssl.name }}/"
  with_fileglob:
      - "{{ ssl.copy_path }}/*"
  when: config.copy_path is defined

- name: Nginx | Copy SSL template
  become: yes
  template:
      src: "{{ ssl.settings_template }}"
      dest: "/etc/nginx/snippets/{{ ssl.name }}/ssl-settings.conf"
  when: ssl.settings_template is defined
