---
- set_fact:
    vhost: "{{ item[0] }}"
    ssl: "{{ item[1] }}"

- name: Clean sites enabled
  file:
      state: absent
      path: "/etc/nginx/sites-enabled/*"
  run_once: true

- name: Nginx | Add SSL config
  include_tasks: ssl.yml
  when:
      - vhost.ssl == True
      - vhost.name == ssl.name

- name: Nginx | Add site config
  become: yes
  template:
      src: "{{ host }}"
      dest: "/etc/nginx/sites-available/{{ vhost.name }}"
  with_first_found:
      - files:
          - "{{ vhost.template }}"
          - default.conf.j2
        skip: false
  loop_control:
      loop_var: host

- name: Nginx | Link config
  become: yes
  file:
      src: "/etc/nginx/sites-available/{{ vhost.name }}"
      dest: "/etc/nginx/sites-enabled/{{ vhost.name }}"
      owner: root
      group: root
      state: link
  notify: restart nginx

- name: Nginx | Check for default config
  stat:
      path: /etc/nginx/sites-enabled/default
  register: default_config

- name: Nginx | Delete the default config
  file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  when:
      - default_config.stat.exists == true
      - nginx_remove_default_config == true