---
- name: restart nginx
  service:
      name: nginx
      enabled: yes
      state: restarted

- name: start nginx
  service:
      name: nginx
      enabled: yes
      state: started

- name: stop nginx
  service:
      name: nginx
      enabled: yes
      state: stopped